language: java
git:
  depth: 99999
matrix:
  include:
  - os: linux
    dist: trusty
    jdk: oraclejdk8
  - os: linux
    dist: trusty
    jdk: oraclejdk9
install:
- true
script:
- mvn install -P wildfly-managed -B -V
